{{- range .Values.roles }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .name }}-role
  labels:
    app: {{ $.Values.name }}
rules:
  {{- range .rules }}
  - apiGroups: {{ .groups | toYaml | nindent 4 }}
    resources: {{ .resources | toYaml | nindent 4 }}
    verbs: {{ .verbs | toYaml | nindent 4 }}
  {{- end }}
---
{{- end }}