{{- range .Values.roles }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .name }}
  labels:
    app: {{ $.Values.name }}
subjects:
  - kind: User
    name: {{ .name }}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .name }}-role
---
{{- end }}