name: api

config:
  nodeEnv: development
  port: 8080
  databaseUrl: postgresql://scrolller:scrolller@db-service/scrolllerdb
  cookieName: session
  redditUrl: https://reddit.com
  webUrl: https://scrolller.vu
  sessionSecret: 0c8304f011c5991a3d3c6525c92f08bc15c863265a882432

image: localhost:32000/api:v1

service:
  type: LoadBalancer
  port: 8080

resources:
  limits:
    memory: "256Mi"
    cpu: "500m"
  requests:
    memory: "128Mi"
    cpu: "250m"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

networkPolicy:
  enabled: true
  ingressPort: 8080
