apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configmap
  namespace: scrolller
  labels:
    app: api
data:
  NODE_ENV: "development"
  PORT: "8080"
  DATABASE_URL: "postgresql://scrolller:scrolller@db-service/scrolllerdb"
  COOKIE_NAME: "session"
  REDDIT_URL: "https://reddit.com"
  WEB_URL: "https://scrolller.vu"
