apiVersion: v1
kind: Service
metadata:
  name: scrolller-api-service
  namespace: scrolller
  labels:
    app: scrolller-api
spec:
  type: LoadBalancer
  selector:
    app: scrolller-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30002
