apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: scrolller-api-hpa
  namespace: scrolller
  labels:
    app: scrolller-api
spec:
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 60
          type: Utilization
      type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scrolller-api-deployment
