apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv-volume
  namespace: scrolller
  labels:
    app: postgres
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/opt/postgres/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pv-claim
  namespace: scrolller
  labels:
    app: postgres
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
