apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-configmap
  labels:
    app: {{ .Values.name }}
data:
  POSTGRES_DB: {{ .Values.config.dbName }}
  POSTGRES_USER: {{ .Values.config.dbUser }}
