apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name }}-pv-volume
  labels:
    app: {{ .Values.name }}
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: {{ .Values.storage.capacity }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: {{ .Values.storage.path | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-pv-claim
  labels:
    app: {{ .Values.name }}
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.capacity }}
