{{- if .Values.canary.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-v3-deployment
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.canary.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
      version: v3
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        version: v3
    spec:
      containers:
        - name: {{ .Values.name }}-container
          image: {{ .Values.canary.image }}
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-v3-service
  labels:
    app: {{ .Values.name }}
    version: v3
spec:
  type: {{ .Values.canary.type }}
  selector:
    app: {{ .Values.name }}
    version: v3
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }} 
{{- end }}