apiVersion: v1
kind: ConfigMap
metadata:
  name: scrolller-web-configmap
  namespace: scrolller
  labels:
    app: scrolller-web
data:
  VITE_API_URL: "http://scrolller-api.scrolller.svc.cluster.local"
