apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-configmap
  labels:
    app: {{ .Values.name }}
data:
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  PORT: {{ .Values.config.port | quote }}
  DATABASE_URL: {{ .Values.config.databaseUrl | quote }}
  COOKIE_NAME: {{ .Values.config.cookieName | quote }}
  REDDIT_URL: {{ .Values.config.redditUrl | quote }}
  WEB_URL: {{ .Values.config.webUrl | quote }}
