apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  labels:
    app: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      initContainers:
        - name: {{ .Values.name }}-migration-container
          image: {{ .Values.image }}
          command: ["npx", "prisma", "db", "push"]
          env:
            - name: DATABASE_URL
              value: {{ .Values.config.databaseUrl | quote }}
      containers:
        - name: {{ .Values.name }}-container
          image: {{ .Values.image }}
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ .Values.name }}-configmap
          env:
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.name }}-secret
                  key: SESSION_SECRET
